config/routes.rb
Rails.application.routes.draw do
  resources :groups do
  	collection { post :import }
  end

  root to: "groups#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
	require 'csv'
	validates :name, presence: true
	has_many :roles
	has_many :users, through: :roles

	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			# byebug
			hsh = row.to_hash
			transaction do
				u = User.find_by(last_name: hsh["last_name"])  #TODO find by full name
				if u.nil?
					u = User.new(first_name: hsh["first_name"], last_name: hsh["last_name"])
					u.save!
				end
				g = Group.find_by(name: hsh["group_name"])
				if g.nil?
					g = Group.new(name: hsh["group_name"])
					g.save!
				end
				r = Role.where("group_id = ? AND user_id = ?", g.id, u.id)
				if r.count == 0
					Role.new(name: hsh["role"], user_id: u.id, group_id: g.id).save!
				end
			end
		end
	end

end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :user
  belongs_to :group
  
  validates :name, presence: true
  scope :organizer, -> (groupid) { where("name IN ('Organizer') AND group_id = ?", groupid) }

end

app/models/user.rb
class User < ApplicationRecord
	has_many :roles
	has_many :groups, through: :roles
	validates :first_name, presence: true
	validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  def import
    Group.import(params[:file])
    redirect_to root_url, notice: "Group data imported!"
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(group) do |f| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Groups</h1>

<table class="table table-striped mt-5">
  <thead>
    <tr>
      <th>Name</th>
      <th>Organizer(s)</th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
          <td><%= link_to group.name, group_path(group.id) %></td>
          <% organizer = group.roles.organizer(group.id) %>
          <% if organizer %><td>
            <% organizer.each do |r| %>
            <div><%= r.user.last_name %>,<%= r.user.first_name %></div>
            <% end %></td>
          <% else %>
            <td></td>
          <% end %>

        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<br/>
<h4>Import Groups</h4>
<%= form_tag import_groups_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import CSV" %>
<% end %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Group:</strong>
  <%= @group.name %>
</p>
<strong>Users:</strong>
<table class="table table-striped mt-5">
	<tbody>
	  <% @group.users.order("roles.name").each do |user| %>
		<tr>
	    <td><%= user.first_name %> <%= user.last_name %></td>
		<td>( <%= user.roles.where(group_id: @group.id, user_id: user.id)[0]["name"] %> )</td>
	</tr>
	  <% end %>
	</tbody>
</table>
<%= link_to 'Back', groups_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a style="background-color: #D6232E;" class="navbar-brand" href="#">N2 Meetups</a>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/groups">Home</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/groups/new">New Group</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlvaroescobarMeetup</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
        <% flash.each do |name, msg| %>
            <%= content_tag(:div, msg, class: "alert alert-info") %>
        <% end %>
        <%= yield %>
    </div>
  </body>
</html>